import Link from "next/link";
import { ArrowRight, CalendarDays, CloudSun, Clock3, Flag, MapPin, Trophy, Users } from "lucide-react";
import { courses, events } from "@/lib/demo-data";

const month=(date:string)=>new Intl.DateTimeFormat("nl-NL",{month:"short"}).format(new Date(date)).replace(".","");
export default function Dashboard(){
  return <div className="page">
    <div className="page-heading"><div><div className="eyebrow"><span/> dinsdag 14 juli</div><h1>Goedemiddag, Sophie.</h1><p>Klaar voor een rondje? De baan ligt er prachtig bij.</p></div></div>
    <div className="dashboard-grid">
      <div><section className="hero"><div className="hero-content"><span className="badge">Ronde van de dag</span><h2>De green roept.<br/>Jij hoeft alleen te spelen.</h2><p>Start een nieuwe scorekaart voor jezelf en maximaal drie medespelers.</p><Link href="/app/play" className="primary-button"><Flag size={16}/> Start een ronde</Link></div><div className="hero-stat"><strong>9</strong><span>holes · par 27</span></div></section>
      <div className="quick-stats"><div className="card stat-card"><small>Beste ronde</small><strong>−2</strong><em>Dit seizoen</em></div><div className="card stat-card"><small>Positie</small><strong>#2</strong><em>+1 deze week</em></div><div className="card stat-card"><small>Rondes</small><strong>18</strong><em>4 deze maand</em></div></div></div>
      <aside className="card weather-card"><div className="weather-top"><div><div className="eyebrow"><span/> Baanconditie</div><h3 style={{margin:"13px 0 5px"}}>Perfect golfweer</h3></div><CloudSun size={40} color="#f3a953"/></div><div className="weather-temp">21°</div><p>Licht bewolkt · Wind 11 km/u</p><div className="weather-hours"><div>14:00<b>21°</b></div><div>16:00<b>22°</b></div><div>18:00<b>20°</b></div><div>20:00<b>18°</b></div></div></aside>
    </div>
    <div className="section-heading"><h2>Binnenkort bij de club</h2><Link href="/app/events">Alle evenementen <ArrowRight size={14}/></Link></div>
    <div className="event-row">{events.map((event,index)=><article className="card event-card" key={event.id}><div className={`event-art ${index===1?"orange":index===2?"blue":""}`}><div className="event-date"><b>{new Date(event.date).getDate()}</b><span>{month(event.date)}</span></div></div><div className="event-body"><h3>{event.title}</h3><div className="event-meta"><span><Clock3 size={11}/>{event.time}</span><span><MapPin size={11}/>{courses.find(c=>c.id===event.courseId)?.name}</span></div><div className="progress"><span style={{width:`${event.registered/event.capacity*100}%`}}/></div><div className="event-footer"><span><Users size={10}/> {event.registered} deelnemers</span><b>{event.capacity-event.registered} plekken vrij</b></div></div></article>)}</div>
    <div className="section-heading"><h2>Jouw club in één oogopslag</h2></div>
    <div className="course-grid"><Link href="/app/leaderboards" className="card course-card" style={{"--course-accent":"#c6f04d"} as React.CSSProperties}><Trophy size={24}/><h3>Weekklassement</h3><p>Je staat op de tweede plaats met een beste ronde van −2.</p><div className="course-meta">Bekijk ranking <ArrowRight size={12}/></div></Link><Link href="/app/courses" className="card course-card" style={{"--course-accent":"#80b8ff"} as React.CSSProperties}><MapPin size={24}/><h3>3 golfbanen</h3><p>Van korte par-3 uitdagingen tot een volledige 18-hole parkbaan.</p><div className="course-meta">Ontdek banen <ArrowRight size={12}/></div></Link><Link href="/app/events" className="card course-card" style={{"--course-accent":"#f3a953"} as React.CSSProperties}><CalendarDays size={24}/><h3>Summer Cup</h3><p>Schrijf je in voor het grootste clubevenement van deze zomer.</p><div className="course-meta">Inschrijven <ArrowRight size={12}/></div></Link></div>
  </div>
}
