"use client";
import { useMemo, useState } from "react";
import { ArrowLeft, Check, ChevronRight, Minus, Plus, Save, UserPlus, WifiOff } from "lucide-react";
import { courses, players } from "@/lib/demo-data";
import { formatToPar } from "@/lib/score";
import { usePersistentState } from "@/hooks/use-persistent-state";

type Stage="setup"|"score"|"submitted";
type ScoreMap=Record<string,number|null>;
export function Scorecard(){
  const [stage,setStage]=useState<Stage>("setup"); const [courseId,setCourseId]=useState(courses[0].id);
  const [playerIds,setPlayerIds]=useState(["me"]); const [scores,setScores]=usePersistentState<Record<string,ScoreMap>>("fairway-active-round",{});
  const [activeHole,setActiveHole]=useState(0); const course=courses.find(c=>c.id===courseId)!;
  const addPlayer=(id:string)=>setPlayerIds(old=>old.includes(id)?old:old.length<4?[...old,id]:old);
  const change=(playerId:string,hole:number,delta:number)=>setScores(old=>{const current=old[playerId]?.[hole];const par=course.layout[hole].par;const next=current==null?Math.max(1,par+(delta<0?-1:0)):Math.min(12,Math.max(1,current+delta));return {...old,[playerId]:{...old[playerId],[hole]:next}}});
  const totals=useMemo(()=>Object.fromEntries(playerIds.map(id=>[id,course.layout.reduce((sum,h,i)=>sum+(scores[id]?.[i]??0),0)])),[course,playerIds,scores]);
  if(stage==="submitted") return <div className="page"><div className="submitted card"><span className="submitted-icon"><Check size={34}/></span><div className="eyebrow"><span/> ronde voltooid</div><h1>Goed gespeeld!</h1><p>Je scorekaart is veilig opgeslagen en wacht op goedkeuring van de club. Zodra de ronde is goedgekeurd, wordt het klassement bijgewerkt.</p><div className="submitted-score"><small>Jouw score</small><strong>{totals.me || "—"}</strong><span>{totals.me?formatToPar(totals.me-course.totalPar):"—"}</span></div><button className="primary-button" onClick={()=>{setStage("setup");setScores({});setActiveHole(0)}}>Terug naar overzicht</button></div></div>;
  if(stage==="setup") return <div className="page"><div className="page-heading"><div><div className="eyebrow"><span/> nieuwe scorekaart</div><h1>Stel je ronde samen.</h1><p>Kies een baan en voeg je flightgenoten toe.</p></div></div><div className="setup-grid"><section><div className="section-heading"><h2>1. Kies je baan</h2></div><div className="course-options">{courses.map(c=><button key={c.id} onClick={()=>setCourseId(c.id)} className={`card course-option ${courseId===c.id?"selected":""}`}><span className="course-orb" style={{background:c.accent}}>{c.holes}</span><span><b>{c.name}</b><small>{c.holes} holes · par {c.totalPar} · tee {c.tee}</small></span>{courseId===c.id&&<Check size={18}/>}</button>)}</div></section><section><div className="section-heading"><h2>2. Wie speelt er?</h2><span className="badge">{playerIds.length}/4 spelers</span></div><div className="player-options"><div className="card selected-player"><span className="avatar">SV</span><span><b>Sophie de Vries</b><small>Jij · TWT-4821</small></span><Check size={17}/></div>{players.filter(p=>p.id!=="me").map(p=><button key={p.id} disabled={playerIds.includes(p.id)} onClick={()=>addPlayer(p.id)} className="card add-player"><span className="avatar">{p.initials}</span><span><b>{p.name}</b><small>{p.code}</small></span>{playerIds.includes(p.id)?<Check size={17}/>:<Plus size={17}/>}</button>)}<button className="guest-button"><UserPlus size={17}/> Gast toevoegen</button></div></section></div><button className="start-round" onClick={()=>setStage("score")}>Start ronde op {course.name}<ChevronRight size={18}/></button></div>;
  const hole=course.layout[activeHole];
  return <div className="score-page"><header className="score-header"><button onClick={()=>setStage("setup")}><ArrowLeft/></button><div><small>{course.name} · {course.tee}</small><b>Hole {hole.number} <span>van {course.holes}</span></b></div><span className="offline-badge"><WifiOff size={12}/> Offline veilig</span></header><div className="hole-progress">{course.layout.map((h,i)=><button aria-label={`Hole ${h.number}`} key={h.number} onClick={()=>setActiveHole(i)} className={`${i===activeHole?"active":""} ${playerIds.every(id=>scores[id]?.[i]!=null)?"done":""}`}>{h.number}</button>)}</div><main className="score-main"><section className="hole-hero"><div><span>HOLE</span><strong>{hole.number}</strong></div><div className="hole-info"><span><small>PAR</small><b>{hole.par}</b></span><i/><span><small>AFSTAND</small><b>{hole.distance} m</b></span></div></section><div className="score-players">{playerIds.map(id=>{const p=players.find(x=>x.id===id)!;const value=scores[id]?.[activeHole];return <article className="card score-player" key={id}><div className="score-person"><span className="avatar">{p.initials}</span><div><b>{p.name}{id==="me"&&<em>Jij</em>}</b><small>Totaal {totals[id]||"—"}</small></div></div><div className="stepper"><button onClick={()=>change(id,activeHole,-1)}><Minus/></button><strong className={value!=null?value<hole.par?"under":value===hole.par?"even":"over":""}>{value??"·"}</strong><button onClick={()=>change(id,activeHole,1)}><Plus/></button></div><div className="score-label">{value==null?"Nog geen score":value===1?"Hole-in-one!":value===hole.par?"Par":value<hole.par?`${hole.par-value} onder par`:`${value-hole.par} boven par`}</div></article>})}</div></main><footer className="score-footer"><button disabled={activeHole===0} onClick={()=>setActiveHole(h=>h-1)}><ArrowLeft/> Vorige</button><div><span>{activeHole+1}/{course.holes}</span></div>{activeHole<course.holes-1?<button className="next" onClick={()=>setActiveHole(h=>h+1)}>Volgende <ChevronRight/></button>:<button className="next" onClick={()=>setStage("submitted")}><Save/> Ronde indienen</button>}</footer></div>;
}
